version: "3.10"

services:
  gprofiler:
    image: granulate/gprofiler:latest
    restart: always
    container_name: "granulate-gprofiler"
    pid: "host"
    userns_mode: "host"
    privileged: true
    command: '-cu --token="<TOKEN>" --service-name="<SERVICE NAME>"'
